
import React ,{useRef}from 'react'

import { useGLTF } from "@react-three/drei";


export default  function Model(props)  {
    const group = useRef();
    const {nodes,materials}=useGLTF('/projectsAssets/brid/models/brid-in-snow.glb')
    const gltf=useGLTF('/projectsAssets/brid/models/brid-in-snow.glb')
    console.log(nodes)
    console.log(gltf);
    return (
        
      <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <group rotation={[0, 0, 0]} >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.carrion_carrion_mat_0.geometry}
            material={materials["carrion_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.carrion001_carrion_hull_mat_0.geometry}
            material={materials["carrion_hull_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.grass_grass_2_mat_0.geometry}
            material={materials["grass_2_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.grass001_grass_1_mat_0.geometry}
            material={materials["grass_1_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.grass002_grass_mat_0.geometry}
            material={materials["grass_mat.002"]}
          />
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0, 2.66, 0]}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.raven001_raven_mat_0.geometry}
                  material={nodes.raven001_raven_mat_0.material}
                />
              </group>
              <primitive object={nodes._rootJoint} />
              <skinnedMesh
                geometry={nodes.Object_21002.geometry}
                material={nodes.Object_21002.material}
                skeleton={nodes.Object_21002.skeleton}
              />
            </group>
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull001_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull001_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull002_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull002_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull003_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull003_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull004_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull004_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull005_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull005_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull006_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull006_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull008_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull008_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull009_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull009_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull010_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull010_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull011_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull011_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull012_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull012_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull013_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull013_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull014_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull014_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull015_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull015_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull016_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull016_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop001_snowdrop_mat_0.geometry}
            material={nodes.snow_drop001_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop002_snowdrop_mat_0.geometry}
            material={nodes.snow_drop002_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop003_snowdrop_mat_0.geometry}
            material={nodes.snow_drop003_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop004_snowdrop_mat_0.geometry}
            material={nodes.snow_drop004_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop005_snowdrop_mat_0.geometry}
            material={nodes.snow_drop005_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop006_snowdrop_mat_0.geometry}
            material={nodes.snow_drop006_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop007_snowdrop_mat_0.geometry}
            material={nodes.snow_drop007_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop008_snowdrop_mat_0.geometry}
            material={nodes.snow_drop008_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop009_snowdrop_mat_0.geometry}
            material={nodes.snow_drop009_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop011_snowdrop_mat_0.geometry}
            material={nodes.snow_drop011_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop012_snowdrop_mat_0.geometry}
            material={nodes.snow_drop012_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop013_snowdrop_mat_0.geometry}
            material={nodes.snow_drop013_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop014_snowdrop_mat_0.geometry}
            material={nodes.snow_drop014_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop015_snowdrop_mat_0.geometry}
            material={nodes.snow_drop015_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop016_snowdrop_mat_0.geometry}
            material={nodes.snow_drop016_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop017_snowdrop_mat_0.geometry}
            material={nodes.snow_drop017_snowdrop_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_drop_hull007_snow_drop_hull_mat_0.geometry}
            material={nodes.snow_drop_hull007_snow_drop_hull_mat_0.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_floor_snow_floor_mat_0.geometry}
            material={materials["snow_floor_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_floor001_snow_floor_hull_mat_0.geometry}
            material={materials["snow_floor_hull_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_pile_snow_pile_mat_0.geometry}
            material={materials["snow_pile_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.snow_pile001_snow_pile_hull_mat_0.geometry}
            material={materials["snow_pile_hull_mat.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.twig_Material003_0.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.twig001_twig_hull_mat_0.geometry}
            material={materials["twig_hull_mat.002"]}
          />
        </group>
      </group>
    </group>
    
    )
}